site_name: B~~~~~Z
site_author: Bin Zhang
site_url: http://binzhango.github.io

repo_name: binzhango/binzhango.github.io
repo_url: https://github.com/binzhango/binzhango.github.io

theme:
  name: material
  favicon: assets/favicon.ico
  features:
    - header.autohide
    - navigation.footer
    - navigation.indexes
    - navigation.top
    - navigation.path
    # - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.tracking
    - content.code.copy
    - content.tabs.link
    # - content.action.view
    - content.code.annotate
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate
  icon:
    logo: logo
  logo: assets/favicon.ico
  logo_bottom: assets/favicon.ico
  font:
    code: Fira Code
    text: Roboto
    
  palette:
    - accent: indigo
      primary: amber
      schema: default
      toggle:
        icon: material/weather-night
        name: Dark Mode
    - accent: indigo
      primary: blue grey
      schema: slate
      toggle:
        icon: material/weather-sunny
        name: Light Mode

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/binzhango
    - icon: material/email
      link: mailto:zhangbinengr@hotmail.com
    - icon: fontawesome/brands/discord
      link: None
  analytics:
    provider: google
    property: G-HLMVZHNEWM

extra_css:
  - stylesheets/extra.css

# nav: #comment nav: it will move archive and categories to new pages
#   # - Home:
#   #     - index.md
#   - Blog:
#       - index.md


plugins:
  - blog:
      blog_dir: .
      # blog_toc: true
      post_dir: "{blog}/posts"
      post_url_date_format: yyyy/MM
      archive_name: Archive
      archive_toc: true
      archive_date_format: yyyy
      archive_url_format: "{date}"
      categories_allowed:
        - python
        - k8s
        - spark
        - ML
        - airflow
        - LLM
        - Azure
        - Snowflake
        - Spark
        - Scala
        - rust

      
  - tags
  - search
  - minify:
      minify_html: true
  - social:
      cards_layout_options:
        background_color: "#ff1439"
  - mkdocs-video:
      css_style:
        height: "27vw"
        width: "48vw"
  - autorefs
  - glightbox

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      auto_title: false
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - tables
  - toc:
      permalink: '#'
